import { describe, expect, it } from 'vitest';
import { applyCustomCss, applyTheme, applyThemeAppearance, DEFAULT_THEME_APPEARANCE, parseThemeAppearance, parseThemeMode, readCustomCss, readThemeMode, resolveTheme, THEME_APPEARANCE_STORAGE_KEY, THEME_STORAGE_KEY, validateCustomCss, writeCustomCss, writeThemeAppearance, writeThemeMode } from '../src/ui/theme/preferences';
describe('theme preferences', () => {
  it('parses invalid values as system', () => { expect(parseThemeMode('dark')).toBe('dark'); expect(parseThemeMode('sepia')).toBe('system'); expect(parseThemeMode(null)).toBe('system'); });
  it('round trips through local storage', () => { const values = new Map<string, string>(); const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } }; writeThemeMode(storage, 'dark'); expect(values.get(THEME_STORAGE_KEY)).toBe('dark'); expect(readThemeMode(storage)).toBe('dark'); });
  it('resolves system mode from OS preference', () => { expect(resolveTheme('system', true)).toBe('dark'); expect(resolveTheme('system', false)).toBe('light'); expect(resolveTheme('light', true)).toBe('light'); });
  it('applies deterministic root attributes', () => { const attrs = new Map<string, string>(); const root = { style: { colorScheme: '' }, setAttribute: (key: string, value: string) => attrs.set(key, value) }; expect(applyTheme('dark', false, root)).toBe('dark'); expect(attrs.get('data-theme')).toBe('dark'); expect(root.style.colorScheme).toBe('dark'); });
  it('validates and persists local custom css without external resources', () => { const values = new Map<string, string>(); const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); }, removeItem: (key: string) => { values.delete(key); } }; expect(validateCustomCss(':root { --accent: red; }')).toEqual([]); expect(validateCustomCss('@import url(https://example.com/theme.css)')).toHaveLength(2); expect(writeCustomCss(storage, 'body { color: red; }')).toEqual([]); expect(readCustomCss(storage)).toContain('color: red'); expect(writeCustomCss(storage, '')).toEqual([]); expect(readCustomCss(storage)).toBe(''); });
  it('applies only valid css to a style element', () => { const head: { children: Element[]; appendChild: (node: Element) => void } = { children: [], appendChild(node) { this.children.push(node); } }; const nodes = new Map<string, HTMLElement>(); const target = { head, getElementById: (id: string) => nodes.get(id) ?? null, createElement: (_tag: string) => { const node = { id: '', textContent: '', remove() { nodes.delete(this.id); }, } as unknown as HTMLStyleElement; Object.defineProperty(node, 'id', { get: () => node.getAttribute?.('id') ?? '', set: (value: string) => { Object.defineProperty(node, 'id', { value, writable: true, configurable: true }); nodes.set(value, node); } }); return node; } } as unknown as Document; applyCustomCss('body { color: red; }', target); expect(head.children).toHaveLength(1); expect((head.children[0] as HTMLStyleElement).textContent).toContain('color: red'); applyCustomCss('url(https://bad.example)', target); expect(head.children).toHaveLength(1); });
  it('normalizes and persists structured appearance', () => { const values = new Map<string, string>(); const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (_key: string) => undefined }; const config = parseThemeAppearance({ messageRadius: 999, playerBubbleBg: '#123456' }); expect(config.messageRadius).toBe(32); expect(config.playerBubbleBg).toBe('#123456'); writeThemeAppearance(storage, config); expect(values.has(THEME_APPEARANCE_STORAGE_KEY)).toBe(true); });
  it('maps appearance values to css variables', () => { const vars = new Map<string, string>(); applyThemeAppearance({ ...DEFAULT_THEME_APPEARANCE, messageRadius: 18 }, { style: { setProperty: (key: string, value: string) => vars.set(key, value) } }); expect(vars.get('--theme-message-radius')).toBe('18px'); });
});
