import { useEffect, useMemo, useState } from 'react';
import { contentDb, deleteCharacter, deletePreset, deleteWorldbook, saveCharacter, savePreset, saveWorldbook } from './data/db/content';
import type { CharacterCard, Preset, WorldbookEntry } from './data/content';
import { exportSaveZip, importSaveZip } from './data/io/zip';
import { SaveFileSchema, type SaveFile } from './data/schema/save';
import { PromptAssembler } from './core/prompt/assembler';
import { providerDb } from './providers/db';
import { ProviderConfigSchema, type ChatMessage, type ProviderConfig } from './providers/types';
import { streamChat } from './providers/stream';
import { testProviderConnection } from './providers/connection-test';
import './ui/theme/app.css';

type Tab = 'map' | 'chat' | 'library' | 'debug';
const now = () => new Date().toISOString();
const slug = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, '-').replace(/^-|-$/g, '') || `item-${Date.now()}`;
const defaultSave: SaveFile = SaveFileSchema.parse({ schemaVersion: 1, meta: { id: 'local-save', title: '我的世界', createdAt: now(), updatedAt: now(), appVersion: '0.0.1' }, config: { calendar: { slots: [{ id: 'morning', name: '早晨', order: 0 }], daysPerWeek: 7, weekdayNames: ['一', '二', '三', '四', '五', '六', '日'], preset: 'standard', unlimitedSlots: false }, actionCosts: {}, axisDefs: [], stageRules: [], showNumbers: false, hiddenTopicStyle: 'hide', realTimeAwareness: false, opsLimitPerTurn: 12 }, world: { clock: { day: 1, slotId: 'morning' }, player: { name: '旅人', nodeId: 'start', stats: {}, flags: {}, inventory: [] } } });

export function App() {
  const [tab, setTab] = useState<Tab>('map'); const [characters, setCharacters] = useState<CharacterCard[]>([]); const [worldbooks, setWorldbooks] = useState<WorldbookEntry[]>([]); const [presets, setPresets] = useState<Preset[]>([]); const [name, setName] = useState(''); const [draftText, setDraftText] = useState(''); const [messages, setMessages] = useState<ChatMessage[]>([]); const [input, setInput] = useState('');
  const [provider, setProvider] = useState<ProviderConfig>({ id: 'default', name: 'Default', kind: 'openai-compatible', endpoint: '', model: '', contextWindow: 8192, maxOutputTokens: 1024, temperature: 0.7 }); const [busy, setBusy] = useState(false); const [debug, setDebug] = useState({ prompt: '', raw: '', ops: '本阶段尚未解析 ops。', state: JSON.stringify(defaultSave, null, 2) });
  useEffect(() => { void Promise.all([contentDb.characters.toArray(), contentDb.worldbooks.toArray(), contentDb.presets.toArray()]).then(([c, w, p]) => { setCharacters(c); setWorldbooks(w); setPresets(p); }); void providerDb.providers.get('default').then((saved) => { if (saved) setProvider(saved); }); }, []);
  const assembler = useMemo(() => { const instance = new PromptAssembler(); instance.register({ id: 'format_contract', role: 'system', priority: 100, order: 0, build: () => '你是一个开放世界叙事游戏的角色，只输出自然语言叙述。' }); instance.register({ id: 'character_core', role: 'system', priority: 95, order: 1, build: () => characters[0] ? `${characters[0].name}\n${characters[0].description}\n${characters[0].personality}` : null }); instance.register({ id: 'worldbook', role: 'system', priority: 80, order: 2, build: () => worldbooks.filter((entry) => entry.enabled).map((entry) => entry.content).join('\n') || null }); return instance; }, [characters, worldbooks]);
  async function sendMessage() { const text = input.trim(); if (!text || busy) return; let parsed: ProviderConfig; try { parsed = ProviderConfigSchema.parse(provider); } catch { setDebug((current) => ({ ...current, raw: '请先填写有效的 Provider endpoint 与 model。' })); return; } const next = [...messages, { role: 'user' as const, content: text }]; setMessages(next); setInput(''); setBusy(true); let assistant = ''; const assembled = assembler.assemble({ input: text }, { budget: Math.max(1, parsed.contextWindow - parsed.maxOutputTokens), task: 'narrate_main' }); setDebug((current) => ({ ...current, prompt: JSON.stringify(assembled, null, 2) })); try { await streamChat(parsed, assembled.messages.concat(next), (delta) => { assistant += delta; setMessages([...next, { role: 'assistant', content: assistant }]); }); setDebug((current) => ({ ...current, raw: assistant })); } catch (error) { setDebug((current) => ({ ...current, raw: error instanceof Error ? error.message : '请求失败' })); } finally { setBusy(false); } }
  async function saveProvider() { const parsed = ProviderConfigSchema.parse(provider); await providerDb.providers.put(parsed); setProvider(parsed); }
  async function testConnection() { try { const parsed = ProviderConfigSchema.parse(provider); const result = await testProviderConnection(parsed); setDebug((current) => ({ ...current, raw: `${result.message}${result.suggestion ? `\n${result.suggestion}` : ''}` })); } catch { setDebug((current) => ({ ...current, raw: '请先填写有效的 Provider endpoint、model 与参数。' })); } }
  async function addContent(kind: 'character' | 'worldbook' | 'preset') { const id = slug(name); if (!name.trim()) return; if (kind === 'character') { const item = await saveCharacter({ id, name, description: draftText, personality: '', updatedAt: now() }); setCharacters((items) => [...items.filter((old) => old.id !== id), item]); } if (kind === 'worldbook') { const item = await saveWorldbook({ id, name, content: draftText, keys: [], enabled: true, priority: 50 }); setWorldbooks((items) => [...items.filter((old) => old.id !== id), item]); } if (kind === 'preset') { const item = await savePreset({ id, name, systemPrompt: draftText, temperature: 0.7, maxOutputTokens: 1024, updatedAt: now() }); setPresets((items) => [...items.filter((old) => old.id !== id), item]); } setName(''); setDraftText(''); }
  async function downloadSave() { const blob = await exportSaveZip(defaultSave, {}, { characters, worldbooks, presets, chat: messages }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'tokimeki-save.zip'; anchor.click(); URL.revokeObjectURL(url); }
  async function loadSave(file?: File) { if (!file) return; try { const imported = await importSaveZip(file); const extra = imported.extras; if (Array.isArray(extra.characters)) setCharacters(extra.characters as CharacterCard[]); if (Array.isArray(extra.worldbooks)) setWorldbooks(extra.worldbooks as WorldbookEntry[]); if (Array.isArray(extra.presets)) setPresets(extra.presets as Preset[]); if (Array.isArray(extra.chat)) setMessages(extra.chat as ChatMessage[]); setDebug((current) => ({ ...current, state: JSON.stringify(imported.save, null, 2), raw: `已导入 ${imported.manifest.type} zip，内容与对话已恢复。` })); } catch (error) { setDebug((current) => ({ ...current, raw: error instanceof Error ? error.message : '导入失败' })); } }
  const onDelete = async (kind: 'character' | 'worldbook' | 'preset', id: string) => { if (kind === 'character') { await deleteCharacter(id); setCharacters((items) => items.filter((item) => item.id !== id)); } if (kind === 'worldbook') { await deleteWorldbook(id); setWorldbooks((items) => items.filter((item) => item.id !== id)); } if (kind === 'preset') { await deletePreset(id); setPresets((items) => items.filter((item) => item.id !== id)); } };
  return <div className="app-shell"><header className="topbar"><div><small>第 1 天 · 早晨</small><h1>Tokimeki</h1></div><button onClick={() => setTab('debug')} aria-label="打开调试面板">调试</button></header><main className="screen">{tab === 'map' && <section className="map-screen"><div className="map-canvas"><span className="map-pin active">你</span><span className="map-pin pin-a">旧市场</span><span className="map-pin pin-b">西码头</span><div className="map-road road-a" /><div className="map-road road-b" /></div><div className="place-card"><span className="eyebrow">当前位置</span><h2>起点街区</h2><p>从地图出发，去遇见今天的世界。</p><button onClick={() => setTab('chat')}>打开聊天</button></div></section>}{tab === 'chat' && <ChatView provider={provider} setProvider={setProvider} onSaveProvider={saveProvider} onTestConnection={testConnection} messages={messages} input={input} setInput={setInput} onSend={sendMessage} busy={busy} />}{tab === 'library' && <LibraryView characters={characters} worldbooks={worldbooks} presets={presets} name={name} setName={setName} draftText={draftText} setDraftText={setDraftText} addContent={addContent} onDelete={onDelete} onExport={downloadSave} onImport={loadSave} />}{tab === 'debug' && <DebugView debug={debug} />}</main><nav className="bottom-nav">{([['map', '地图'], ['chat', '聊天'], ['library', '资料'], ['debug', '调试']] as const).map(([id, label]) => <button key={id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav></div>;
}
function ChatView(props: { provider: ProviderConfig; setProvider: (provider: ProviderConfig) => void; onSaveProvider: () => Promise<void>; onTestConnection: () => Promise<void>; messages: ChatMessage[]; input: string; setInput: (value: string) => void; onSend: () => Promise<void>; busy: boolean }) { return <section className="chat-screen"><div className="section-heading"><div><span className="eyebrow">日常相遇</span><h2>与角色聊天</h2></div><span className="status-dot">{props.busy ? '生成中' : '在线'}</span></div><div className="provider-card"><strong>Provider</strong><input placeholder="Endpoint URL" value={props.provider.endpoint} onChange={(event) => props.setProvider({ ...props.provider, endpoint: event.target.value })} /><input placeholder="Model" value={props.provider.model} onChange={(event) => props.setProvider({ ...props.provider, model: event.target.value })} /><input placeholder="API key（仅本地）" type="password" value={props.provider.apiKey ?? ''} onChange={(event) => props.setProvider({ ...props.provider, apiKey: event.target.value })} /><div className="button-row"><button onClick={() => void props.onSaveProvider()}>保存 Provider</button><button onClick={() => void props.onTestConnection()}>连接测试</button></div></div><div className="messages">{props.messages.length === 0 && <p className="empty">配置 Provider 后发送第一句话。</p>}{props.messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}</div><div className="composer"><textarea value={props.input} onChange={(event) => props.setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void props.onSend(); } }} placeholder="说点什么……" /><button onClick={() => void props.onSend()} disabled={props.busy}>发送</button></div></section>; }
function LibraryView(props: { characters: CharacterCard[]; worldbooks: WorldbookEntry[]; presets: Preset[]; name: string; setName: (value: string) => void; draftText: string; setDraftText: (value: string) => void; addContent: (kind: 'character' | 'worldbook' | 'preset') => Promise<void>; onDelete: (kind: 'character' | 'worldbook' | 'preset', id: string) => Promise<void>; onExport: () => Promise<void>; onImport: (file?: File) => Promise<void> }) { return <section><div className="section-heading"><div><span className="eyebrow">本地资料</span><h2>角色 / 世界书 / 预设</h2></div></div><div className="editor-card"><input placeholder="名称" value={props.name} onChange={(event) => props.setName(event.target.value)} /><textarea placeholder="描述或内容" value={props.draftText} onChange={(event) => props.setDraftText(event.target.value)} /><div className="button-row"><button onClick={() => void props.addContent('character')}>新增角色</button><button onClick={() => void props.addContent('worldbook')}>新增世界书</button><button onClick={() => void props.addContent('preset')}>新增预设</button></div></div><ContentList title="角色卡" items={props.characters} onDelete={(id) => props.onDelete('character', id)} /><ContentList title="世界书" items={props.worldbooks} onDelete={(id) => props.onDelete('worldbook', id)} /><ContentList title="预设" items={props.presets} onDelete={(id) => props.onDelete('preset', id)} /><div className="io-card"><button onClick={() => void props.onExport()}>导出 save.zip</button><label className="file-button">导入 zip<input type="file" accept=".zip" onChange={(event) => void props.onImport(event.target.files?.[0])} /></label></div></section>; }
function ContentList({ title, items, onDelete }: { title: string; items: Array<{ id: string; name: string }>; onDelete: (id: string) => Promise<void> }) { return <div className="list-card"><h3>{title}</h3>{items.length === 0 ? <p className="empty">暂无内容</p> : items.map((item) => <div className="list-row" key={item.id}><span>{item.name}</span><button onClick={() => void onDelete(item.id)}>删除</button></div>)}</div>; }
function DebugView({ debug }: { debug: { prompt: string; raw: string; ops: string; state: string } }) { return <section><div className="section-heading"><div><span className="eyebrow">开发工具</span><h2>调试面板</h2></div></div><div className="debug-tabs"><article><h3>Prompt</h3><pre>{debug.prompt || '尚未组装 prompt'}</pre></article><article><h3>Raw</h3><pre>{debug.raw || '尚未收到回复'}</pre></article><article><h3>Ops</h3><pre>{debug.ops}</pre></article><article><h3>State</h3><pre>{debug.state}</pre></article></div></section>; }
